# Generated by Django 4.2.5 on 2023-11-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='company')),
                ('call_us', models.CharField(max_length=100)),
                ('email_us', models.CharField(max_length=100)),
                ('subtitle', models.TextField(max_length=500)),
                ('fb_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('insta_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('emails', models.TextField(max_length=100)),
                ('phones', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=150)),
                ('android_link', models.URLField(blank=True, null=True)),
                ('ios_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
