# Generated by Django 4.2.5 on 2023-09-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('subtitle', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=100000)),
                ('image', models.ImageField(upload_to='products')),
                ('price', models.FloatField()),
                ('flag', models.CharField(max_length=10)),
                ('sku', models.CharField(max_length=12)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
